apiVersion: v1
kind: Service
metadata:
  name: spring-containerization
spec:
  selector:
    app: spring-containerization
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer